version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=django
      - POSTGRES_USER=srchoi
      - POSTGRES_PASSWORD=God30526..
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=django
      - POSTGRES_USER=srchoi
      - POSTGRES_PASSWORD=God30526..
    depends_on:
      - db
  jupyter:
    image: srchoi/jupyter:210119
    volumes:
      - .:/home/jovyan/work
    ports:
      - "18888:8888"
